# Generated by Django 4.2.2 on 2023-06-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_alter_product_photo_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Дитячі товари', 'verbose_name_plural': 'Дитячі товари'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
