# Generated by Django 4.2.2 on 2023-06-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0008_alter_order_options_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default=1, max_length=100, verbose_name='Товари'),
            preserve_default=False,
        ),
    ]
