# Generated by Django 4.2.2 on 2023-06-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0012_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
            ],
            options={
                'verbose_name': "Зворотний зв'язок",
                'verbose_name_plural': "Зворотний зв'язок",
                'ordering': ['created_at'],
            },
        ),
    ]
