# Generated by Django 4.2.2 on 2023-06-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0014_alter_feedback_options_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
